"""empty message

Revision ID: cadc6e34813d
Revises: 
Create Date: 2019-10-29 22:47:38.583113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadc6e34813d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('short_url', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_short_url'), 'urls', ['short_url'], unique=True)
    op.create_index(op.f('ix_urls_url'), 'urls', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_url'), table_name='urls')
    op.drop_index(op.f('ix_urls_short_url'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
